version: '3.8'

services:
  react-app:
    image: timiliris/blueprint:latest
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      MEILISEARCH_URL: https://meilisearch.blueprint-create.net/
      MEILISEARCH_API_KEY: HFNtHry2u3j6ykqxcC5hd1QRIskufFU2F8R44aSVgUBLF5LVtB0nxMGkENQaMtHPYG7IGCl3CkDKtn93xG8wIi6dZRgiyF470EaB16cBcREL5Zlm9V9dmaR5qutZXQu3
      APPWRITE_URL: https://api.blueprint-create.com/v1
      APPWRITE_PROJECT_ID: 67ad0767000d58bb6592
