name: 🔥 Hot-Fix
description: Critical issue requiring immediate attention
labels: ["priority: critical"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this critical issue!
  
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Clearly describe the issue and its impact
      placeholder: The issue is causing...
    validations:
      required: true
      
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. Observe...
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true
      
  - type: textarea
    id: affected
    attributes:
      label: Affected Areas
      description: Which features or functionality are impacted?
    validations:
      required: true
      
  - type: textarea
    id: workaround
    attributes:
      label: Possible Workaround
      description: Is there any temporary solution until this is fixed?
    validations:
      required: false
  
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I have confirmed this is a critical issue requiring immediate attention
          required: true
