name: 🎨 Design
description: Suggest changes to UI/UX or visual elements
title: "[DESIGN]: "
labels: ["design"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve the design of Blueprint!
  
  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the design element that needs improvement?
      placeholder: The UI component at...
    validations:
      required: true
      
  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What is the design issue or opportunity?
      placeholder: The current design...
    validations:
      required: true
      
  - type: textarea
    id: improvement
    attributes:
      label: Suggested Improvement
      description: What would you like to see changed or added?
    validations:
      required: true
      
  - type: dropdown
    id: impact
    attributes:
      label: Impact Areas
      description: What areas would this design change impact?
      multiple: true
      options:
        - Visual appearance
        - Accessibility
        - User workflow
        - Responsiveness
        - Layout
        - Theme support
        - Consistency
    validations:
      required: true
      
  - type: textarea
    id: mockups
    attributes:
      label: Mockups or References
      description: If available, provide mockups or reference examples
      placeholder: Here's how it could look...
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the design suggestion here
    validations:
      required: false
