name: 🔧 Infrastructure
description: Suggest improvements to development processes or tooling
labels: ["infrastructure"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our development infrastructure!
  
  - type: dropdown
    id: area
    attributes:
      label: Infrastructure Area
      description: What area of infrastructure needs improvement?
      options:
        - Build process
        - CI/CD pipeline
        - Development environment
        - Testing framework
        - Deployment process
        - Performance monitoring
        - Package management
        - Code quality tools
        - Other
    validations:
      required: true
      
  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What is the infrastructure issue or opportunity?
      placeholder: The current process...
    validations:
      required: true
      
  - type: textarea
    id: improvement
    attributes:
      label: Suggested Improvement
      description: What would you like to see changed or added?
    validations:
      required: true
      
  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What benefits would this change bring?
      placeholder: This change would improve...
    validations:
      required: true
      
  - type: textarea
    id: drawbacks
    attributes:
      label: Potential Drawbacks
      description: Are there any downsides to consider?
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the infrastructure request here
    validations:
      required: false
