blank_issues_enabled: false
contact_links:
  - name: Blueprint Discord Community
    url: https://discord.gg/kDa8YC8u5J
    about: For questions or discussions about Blueprint, join our Discord server!
